HSC-312: Add form translations
mekomsolutions/ozone-hsc pull request #62
Opened 2024-12-16 11:19 UTC by usamaidrsk

https://mekomsolutions.atlassian.net/browse/HSC-312

2024-12-16 12:02 UTC, usamaidrsk commented
https://github.com/user-attachments/assets/9477353c-6952-4ea6-b345-6fd95055b6d8

2024-12-17 12:06 UTC, kazlaw approved these changes
All looks okay  https://drive.google.com/file/d/1_67fYgGXxXncst_SfKPlxzrMkjA3Eng0/view?usp=sharing

2024-12-18 08:51 UTC, Ruhanga requested changes
Great work, @usamaidrsk! Could you also include the Form Name translation within each file? Please refer to [this document](https://github.com/mekomsolutions/openmrs-module-initializer/blob/main/readme/ampathformstranslations.md) for guidance. The format should look something like this in one of the en language files (similar to how it will be done for the fr language):

```
  "description": "Vaccinations",
  "form": "Motif de consultation",
  "form_name_translation": "Reason for consultation",
  "language": "en",
  ..
  ...
```

2024-12-19 08:56 UTC, Ruhanga approved these changes

2024-12-19 09:42 UTC, merged